Add rule
APIYOJENNIFER/react-scratch-query-builder pull request #5
Opened 2023-06-05 10:36 UTC by APIYOJENNIFER

Issue #1 

- Add a rule
- Handle Field and operator select options
- Handle validation of input fields
- Handle deletion of a rule

2023-06-07 12:25 UTC, ThatcherK requested changes
Am getting this error when I run the application
<img width="1428" alt="Screenshot 2023-06-07 at 15 24 23" src="https://github.com/APIYOJENNIFER/react-scratch-query-builder/assets/32189973/16a6473a-0b19-40b8-bcc9-850e0e86b78f">

2023-06-07 12:25 UTC, ThatcherK commented on src/components/Error.tsx
> +  isValid;
Why don't these props have types ideally that would render the interface useless? For example `isValid: boolean` and so forth. Or is this a new syntax I don't know about?

2023-06-07 12:25 UTC, ThatcherK commented on src/components/GeneralButton.tsx
> +const GeneralButton = ({ ...props }: ButtonProps) => (
Include return type for the component

2023-06-07 12:25 UTC, ThatcherK commented on src/components/Logical.tsx
> +const Logical = ({ ...props }: LogicalProps) => {
Include component return type

2023-06-07 12:25 UTC, ThatcherK commented on src/components/Rule.tsx
> +  rules: {
Here you could have an interface called Rule  and then use it inside RuleProps like this `interface RuleProps {rules:Rule[]}`.That makes it easier to re-use `Rule` anywhere else in the code base

2023-06-07 13:04 UTC, APIYOJENNIFER commented on src/components/Error.tsx
> +  isValid;
I had instances where the type would be inferred and I didn't need to explicitly annotate it but it's not the case here. Let me fix it

2023-06-08 15:31 UTC, ThatcherK approved these changes

2023-06-08 15:32 UTC, merged